import { Demographic } from '../types/user';

export const dialects: Array<Demographic> = [
    { id: 'hardmaeli', name: 'Harðmæli' },
    { id: 'raddadur-framburdur', name: 'Raddaður framburður' },
    { id: 'ngl-framburdur', name: 'ngl-framburður' },
    { id: 'bd-gd-framburdur', name: 'bð/gð-framburður' },
    {
        id: 'vestfirskur-einhljodaframburdur',
        name: 'Vestfirskur einhljóðaframburður',
    },
    { id: 'versfirsk-ahersla', name: 'Vestfirsk áhersla' },
    { id: 'hv-framburdur', name: 'hv-framburður' },
    {
        id: 'skaftfellskur-einhljodaframburdur',
        name: 'Skaftfellskur einhljóðaframburður',
    },
    { id: 'rn-rl-framburdur', name: 'rn/rl-framburður' },
];

// TODO: add translation for under 18
export const ages: Array<Demographic> = [
    { id: 'barn', name: 'undir 18' },
    { id: 'unglingur', name: '18-19' },
    { id: 'tvitugt', name: '20-29' },
    { id: 'thritugt', name: '30-39' },
    { id: 'fertugt', name: '40-49' },
    { id: 'fimmtugt', name: '50-59' },
    { id: 'sextugt', name: '60-69' },
    { id: 'sjotugt', name: '70-79' },
    { id: 'attraett', name: '80-89' },
    { id: 'niraett', name: '90+' },
];

export const genders: Array<Demographic> = [
    { id: 'karl', name: 'genders.male' },
    { id: 'kona', name: 'genders.female' },
    { id: 'annad', name: 'genders.other' },
];

export const nativeLanguages: Array<Demographic> = [
    { id: 'albanska', name: 'languages.albanska' },
    { id: 'arabiska', name: 'languages.arabiska' },
    { id: 'bulgarska', name: 'languages.bulgarska' },
    { id: 'danska', name: 'languages.danska' },
    { id: 'eistneska', name: 'languages.eistneska' },
    { id: 'enska', name: 'languages.enska' },
    { id: 'faereyska', name: 'languages.faereyska' },
    { id: 'filippseyskt_mal', name: 'languages.filippseyskt_mal' },
    { id: 'finnska', name: 'languages.finnska' },
    { id: 'franska', name: 'languages.franska' },
    { id: 'graenlenska', name: 'languages.graenlenska' },
    { id: 'griska', name: 'languages.griska' },
    { id: 'hebreska', name: 'languages.hebreska' },
    { id: 'hindi', name: 'languages.hindi' },
    { id: 'hollenska', name: 'languages.hollenska' },
    { id: 'indonesiska', name: 'languages.indonesiska' },
    { id: 'islenska', name: 'languages.islenska' },
    { id: 'italska', name: 'languages.italska' },
    { id: 'japanska', name: 'languages.japanska' },
    { id: 'katalonska', name: 'languages.katalonska' },
    { id: 'kinverska', name: 'languages.kinverska' },
    { id: 'koreska', name: 'languages.koreska' },
    { id: 'kurdiska', name: 'languages.kurdiska' },
    { id: 'lettneska', name: 'languages.lettneska' },
    { id: 'litaiska', name: 'languages.litaiska' },
    { id: 'makedonska', name: 'languages.makedonska' },
    { id: 'mongolska', name: 'languages.mongolska' },
    { id: 'nepalska', name: 'languages.nepalska' },
    { id: 'norska', name: 'languages.norska' },
    { id: 'persneska', name: 'languages.persneska' },
    { id: 'polska', name: 'languages.polska' },
    { id: 'portugalska', name: 'languages.portugalska' },
    { id: 'rumenska', name: 'languages.rumenska' },
    { id: 'russneska', name: 'languages.russneska' },
    { id: 'saenska', name: 'languages.saenska' },
    { id: 'serbokroatiska', name: 'languages.serbokroatiska' },
    { id: 'singhalesiska', name: 'languages.singhalesiska' },
    { id: 'slovakiska', name: 'languages.slovakiska' },
    { id: 'slovenska', name: 'languages.slovenska' },
    { id: 'spaenska', name: 'languages.spaenska' },
    { id: 'svahili', name: 'languages.svahili' },
    { id: 'tailenska', name: 'languages.tailenska' },
    { id: 'tamil', name: 'languages.tamil' },
    { id: 'tekkneska', name: 'languages.tekkneska' },
    { id: 'thyska', name: 'languages.thyska' },
    { id: 'tyrkneska', name: 'languages.tyrkneska' },
    { id: 'ukrainska', name: 'languages.ukrainska' },
    { id: 'ungverska', name: 'languages.ungverska' },
    { id: 'urdu', name: 'languages.urdu' },
    { id: 'vietnamska', name: 'languages.vietnamska' },
    { id: 'annad', name: 'languages.annad' },
];
