import {
    AgeStat,
    GenderStat,
    ScoreboardData,
    TimelineStat,
} from '../types/competition';

export const scoreboard: ScoreboardData[] = [
    {
        name: 'ELKO',
        size: 'medium',
        users: 145,
        count: 47896,
        rank: 1,
    },
    {
        name: 'Menntaskólinn á Tröllaskaga',
        size: 'small',
        users: 33,
        count: 42470,
        rank: 2,
    },
    {
        name: 'Kerecis hf',
        size: 'small',
        users: 64,
        count: 33657,
        rank: 3,
    },
    {
        name: 'Smáraskóli',
        size: 'small',
        users: 54,
        count: 30070,
        rank: 4,
    },
    {
        name: 'RÚV',
        size: 'medium',
        users: 127,
        count: 25113,
        rank: 5,
    },
    {
        name: 'Fjölbrautaskólinn í Breiðholti',
        size: 'medium',
        users: 88,
        count: 18904,
        rank: 6,
    },
    {
        name: 'Stapaskóli',
        size: 'medium',
        users: 53,
        count: 15451,
        rank: 7,
    },
    {
        name: 'Advania',
        size: 'large',
        users: 154,
        count: 10250,
        rank: 8,
    },
    {
        name: 'Álfhólsskóli',
        size: 'small',
        users: 45,
        count: 9497,
        rank: 9,
    },
    {
        name: 'Borgarholtsskóli',
        size: 'medium',
        users: 76,
        count: 9003,
        rank: 10,
    },
    {
        name: 'Háskólinn á Akureyri',
        size: 'medium',
        users: 62,
        count: 6803,
        rank: 11,
    },
    {
        name: 'Íslandsbanki',
        size: 'large',
        users: 132,
        count: 5270,
        rank: 12,
    },
    {
        name: 'ÖBÍ',
        size: 'small',
        users: 11,
        count: 4835,
        rank: 13,
    },
    {
        name: 'Verkmenntaskólinn á Akureyri',
        size: 'medium',
        users: 41,
        count: 3874,
        rank: 14,
    },
    {
        name: 'TDK Foil Iceland',
        size: 'medium',
        users: 15,
        count: 3514,
        rank: 15,
    },
    {
        name: 'IÐAN fræðslusetur',
        size: 'small',
        users: 8,
        count: 3395,
        rank: 16,
    },
    {
        name: 'Heyrnar- og talmeinastöð Íslands',
        size: 'small',
        users: 10,
        count: 3362,
        rank: 17,
    },
    {
        name: '-',
        size: 'medium',
        users: 103,
        count: 3055,
        rank: 18,
    },
    {
        name: 'F32',
        size: 'small',
        users: 1,
        count: 3041,
        rank: 19,
    },
    {
        name: 'Breið þróunarfélag ',
        size: 'small',
        users: 14,
        count: 2802,
        rank: 20,
    },
    {
        name: 'Lundarskóli',
        size: 'small',
        users: 15,
        count: 2769,
        rank: 21,
    },
    {
        name: 'Keilir',
        size: 'small',
        users: 27,
        count: 2751,
        rank: 22,
    },
    {
        name: 'Lýsi hf',
        size: 'medium',
        users: 3,
        count: 2574,
        rank: 23,
    },
    {
        name: 'Reykjavíkurborg',
        size: 'large',
        users: 68,
        count: 2447,
        rank: 24,
    },
    {
        name: 'Vinnumálastofnun',
        size: 'medium',
        users: 47,
        count: 2438,
        rank: 25,
    },
    {
        name: 'Íþróttasamband fatlaðra',
        size: 'small',
        users: 12,
        count: 2283,
        rank: 26,
    },
    {
        name: 'Reykjanesbær  - Ráðhús',
        size: 'small',
        users: 31,
        count: 2116,
        rank: 27,
    },
    {
        name: 'Síminn',
        size: 'large',
        users: 56,
        count: 2110,
        rank: 28,
    },
    {
        name: 'Félag Lesblindra á Íslandi',
        size: 'small',
        users: 28,
        count: 2045,
        rank: 29,
    },
    {
        name: 'Borgarbyggð - ráðhús',
        size: 'small',
        users: 23,
        count: 1874,
        rank: 30,
    },
    {
        name: 'TVIST',
        size: 'small',
        users: 10,
        count: 1844,
        rank: 31,
    },
    {
        name: 'Skopos ehf.',
        size: 'small',
        users: 12,
        count: 1825,
        rank: 32,
    },
    {
        name: 'LS Retail',
        size: 'medium',
        users: 24,
        count: 1641,
        rank: 33,
    },
    {
        name: 'Fjölbrautaskóli Snæfellinga',
        size: 'small',
        users: 17,
        count: 1575,
        rank: 34,
    },
    {
        name: 'Bændasamtök Íslands',
        size: 'small',
        users: 18,
        count: 1429,
        rank: 35,
    },
    {
        name: 'EFLA',
        size: 'large',
        users: 29,
        count: 1400,
        rank: 36,
    },
    {
        name: 'Langholtsskóli',
        size: 'medium',
        users: 22,
        count: 1372,
        rank: 37,
    },
    {
        name: 'Vinnueftirlitið',
        size: 'small',
        users: 6,
        count: 1361,
        rank: 38,
    },
    {
        name: 'Reykjalundur',
        size: 'medium',
        users: 40,
        count: 1361,
        rank: 39,
    },
    {
        name: 'Domino’s',
        size: 'large',
        users: 55,
        count: 1265,
        rank: 40,
    },
    {
        name: 'OR-samstæðan',
        size: 'large',
        users: 24,
        count: 1242,
        rank: 41,
    },
    {
        name: 'Heima',
        size: 'small',
        users: 21,
        count: 1226,
        rank: 42,
    },
    {
        name: 'Fjölmennt',
        size: 'small',
        users: 7,
        count: 1152,
        rank: 43,
    },
    {
        name: 'Fjölbrautaskólanum við Ármúla',
        size: 'medium',
        users: 3,
        count: 1112,
        rank: 44,
    },
    {
        name: 'Tæknivörur - Samsung Mobile á Íslandi',
        size: 'small',
        users: 14,
        count: 1078,
        rank: 45,
    },
    {
        name: 'Landgræðslan',
        size: 'small',
        users: 13,
        count: 1028,
        rank: 46,
    },
    {
        name: 'Laugarnesskóli',
        size: 'medium',
        users: 23,
        count: 970,
        rank: 47,
    },
    {
        name: 'Hörðuvallaskóli ',
        size: 'medium',
        users: 9,
        count: 852,
        rank: 48,
    },
    {
        name: 'SPURNING.is        Námsráðgjöf og bókaútgáfa',
        size: 'small',
        users: 13,
        count: 816,
        rank: 49,
    },
    {
        name: 'Háskólinn í Reykjavík',
        size: 'large',
        users: 25,
        count: 813,
        rank: 50,
    },
    {
        name: 'Tannlæknastofan ',
        size: 'small',
        users: 1,
        count: 810,
        rank: 51,
    },
    {
        name: 'Leikskóli Seltjarnarness',
        size: 'medium',
        users: 13,
        count: 798,
        rank: 52,
    },
    {
        name: 'Háskóli Íslands',
        size: 'large',
        users: 23,
        count: 784,
        rank: 53,
    },
    {
        name: 'Sveitarfélagið Árborg',
        size: 'large',
        users: 17,
        count: 756,
        rank: 54,
    },
    {
        name: 'Hreyfill',
        size: 'small',
        users: 9,
        count: 718,
        rank: 55,
    },
    {
        name: 'Össur',
        size: 'large',
        users: 19,
        count: 705,
        rank: 56,
    },
    {
        name: 'Sviðslistadeild LHÍ',
        size: 'small',
        users: 12,
        count: 676,
        rank: 57,
    },
    {
        name: 'Rannsóknamiðstöð Íslands - Rannís',
        size: 'small',
        users: 10,
        count: 628,
        rank: 58,
    },
    {
        name: 'Menntaskólinn á Egilsstöðum',
        size: 'medium',
        users: 10,
        count: 618,
        rank: 59,
    },
    {
        name: 'Icelandair',
        size: 'large',
        users: 14,
        count: 614,
        rank: 60,
    },
    {
        name: 'Menntaskóli Borgarfjarðar',
        size: 'small',
        users: 12,
        count: 610,
        rank: 61,
    },
    {
        name: 'Ráðgjafarmiðstöð landbúnaðarins',
        size: 'small',
        users: 5,
        count: 579,
        rank: 62,
    },
    {
        name: 'Hornsteinn ',
        size: 'medium',
        users: 4,
        count: 551,
        rank: 63,
    },
    {
        name: 'Fjölbrautaskóli Suðurnesja',
        size: 'medium',
        users: 23,
        count: 543,
        rank: 64,
    },
    {
        name: 'SAHARA',
        size: 'small',
        users: 6,
        count: 492,
        rank: 65,
    },
    {
        name: 'Klettaskóli',
        size: 'small',
        users: 8,
        count: 471,
        rank: 66,
    },
    {
        name: 'Rúmfatalagerinn',
        size: 'medium',
        users: 9,
        count: 463,
        rank: 67,
    },
    {
        name: 'Heilbrigðisstofnun Austurlands',
        size: 'medium',
        users: 4,
        count: 461,
        rank: 68,
    },
    {
        name: 'Sjónstöðin -Þjónustu- og þekkingarmiðstöð',
        size: 'small',
        users: 9,
        count: 451,
        rank: 69,
    },
    {
        name: 'Ey ehf',
        size: 'small',
        users: 4,
        count: 451,
        rank: 70,
    },
    {
        name: 'Lágafellsskóli',
        size: 'medium',
        users: 10,
        count: 451,
        rank: 71,
    },
    {
        name: 'Múlalundur ',
        size: 'small',
        users: 3,
        count: 444,
        rank: 72,
    },
    {
        name: 'Reiknistofa Bankanna',
        size: 'medium',
        users: 11,
        count: 438,
        rank: 73,
    },
    {
        name: 'Héraðsdómur Reykjavíkur',
        size: 'small',
        users: 11,
        count: 408,
        rank: 74,
    },
    {
        name: '.',
        size: 'small',
        users: 16,
        count: 392,
        rank: 75,
    },
    {
        name: 'Vörður tryggingar',
        size: 'medium',
        users: 13,
        count: 378,
        rank: 76,
    },
    {
        name: 'Skipulagsstofnun',
        size: 'small',
        users: 8,
        count: 346,
        rank: 77,
    },
    {
        name: 'Hæfingarstöðin Reykjanesbæ',
        size: 'small',
        users: 4,
        count: 342,
        rank: 78,
    },
    {
        name: 'Kópavogsbær',
        size: 'small',
        users: 8,
        count: 336,
        rank: 79,
    },
    {
        name: 'Samgöngu- og sveitarstjórnarráðuneytið',
        size: 'small',
        users: 8,
        count: 330,
        rank: 80,
    },
    {
        name: 'Umhverfis- og auðlindaráðuneytið',
        size: 'small',
        users: 10,
        count: 325,
        rank: 81,
    },
    {
        name: 'Sjálfstæður atvinnurekandi',
        size: 'small',
        users: 12,
        count: 317,
        rank: 82,
    },
    {
        name: 'Menntaskólinn í Kópavogi',
        size: 'medium',
        users: 8,
        count: 306,
        rank: 83,
    },
    {
        name: 'Hafnarfjarðarbær',
        size: 'large',
        users: 12,
        count: 305,
        rank: 84,
    },
    {
        name: 'Lögreglan á höfuðborgarsvæðinu',
        size: 'large',
        users: 13,
        count: 302,
        rank: 85,
    },
    {
        name: 'Valitor',
        size: 'medium',
        users: 6,
        count: 292,
        rank: 86,
    },
    {
        name: 'Náttúrustofa Austurlands',
        size: 'small',
        users: 3,
        count: 280,
        rank: 87,
    },
    {
        name: 'Marel',
        size: 'large',
        users: 7,
        count: 279,
        rank: 88,
    },
    {
        name: 'Eirberg - Stuðlaberg heilbrigðistækni ehf.',
        size: 'small',
        users: 8,
        count: 266,
        rank: 89,
    },
    {
        name: 'Mjólkursamsalan ehf',
        size: 'large',
        users: 12,
        count: 265,
        rank: 90,
    },
    {
        name: 'Barnaskólinn á Eyrarbakka og Stokkseyri',
        size: 'small',
        users: 10,
        count: 263,
        rank: 91,
    },
    {
        name: 'Fræðslunetið símenntun á Suðurlandi',
        size: 'small',
        users: 3,
        count: 260,
        rank: 92,
    },
    {
        name: 'Á eftirlaunum',
        size: 'small',
        users: 13,
        count: 250,
        rank: 93,
    },
    {
        name: 'The Tin Can Factory',
        size: 'small',
        users: 3,
        count: 247,
        rank: 94,
    },
    {
        name: 'Creditinfo Lánstraust',
        size: 'small',
        users: 6,
        count: 242,
        rank: 95,
    },
    {
        name: 'Urriðaholtsskóli ',
        size: 'medium',
        users: 4,
        count: 239,
        rank: 96,
    },
    {
        name: 'Menntamálastofnun',
        size: 'small',
        users: 8,
        count: 232,
        rank: 97,
    },
    {
        name: 'Origo',
        size: 'large',
        users: 10,
        count: 223,
        rank: 98,
    },
    {
        name: 'Mandala',
        size: 'small',
        users: 2,
        count: 220,
        rank: 99,
    },
    {
        name: 'Sindri',
        size: 'small',
        users: 3,
        count: 211,
        rank: 100,
    },
    {
        name: 'Fisktækniskóli Íslands',
        size: 'small',
        users: 4,
        count: 206,
        rank: 101,
    },
    {
        name: 'Isavia',
        size: 'large',
        users: 6,
        count: 203,
        rank: 102,
    },
    {
        name: 'Búseti',
        size: 'small',
        users: 4,
        count: 199,
        rank: 103,
    },
    {
        name: 'Listahátíð í Reykjavík',
        size: 'small',
        users: 2,
        count: 197,
        rank: 104,
    },
    {
        name: 'Bóndi',
        size: 'small',
        users: 12,
        count: 182,
        rank: 105,
    },
    {
        name: 'Grunnskóli Fáskrúðsfjarðar ',
        size: 'small',
        users: 7,
        count: 181,
        rank: 106,
    },
    {
        name: 'Bíll 56 ehf',
        size: 'small',
        users: 1,
        count: 169,
        rank: 107,
    },
    {
        name: 'Fagkaup / Vatn og veitur',
        size: 'small',
        users: 2,
        count: 166,
        rank: 108,
    },
    {
        name: 'Landhelgisgæsla Íslands',
        size: 'medium',
        users: 2,
        count: 164,
        rank: 109,
    },
    {
        name: 'Samherji hf',
        size: 'large',
        users: 5,
        count: 163,
        rank: 110,
    },
    {
        name: 'Ísljós ehf.',
        size: 'small',
        users: 1,
        count: 159,
        rank: 111,
    },
    {
        name: 'Borgarhólsskóli',
        size: 'small',
        users: 11,
        count: 153,
        rank: 112,
    },
    {
        name: 'VIRK',
        size: 'small',
        users: 8,
        count: 152,
        rank: 113,
    },
    {
        name: 'Nesskóli',
        size: 'small',
        users: 5,
        count: 151,
        rank: 114,
    },
    {
        name: 'Hafrannsóknastofnun',
        size: 'medium',
        users: 3,
        count: 149,
        rank: 115,
    },
    {
        name: 'Garðabær',
        size: 'large',
        users: 3,
        count: 148,
        rank: 116,
    },
    {
        name: 'Öryggismiðstöð Íslands',
        size: 'medium',
        users: 3,
        count: 146,
        rank: 117,
    },
    {
        name: 'Crayon',
        size: 'small',
        users: 5,
        count: 139,
        rank: 118,
    },
    {
        name: 'Víðistaðaskóli',
        size: 'medium',
        users: 3,
        count: 138,
        rank: 119,
    },
    {
        name: 'Reykholtsskóli',
        size: 'small',
        users: 2,
        count: 138,
        rank: 120,
    },
    {
        name: 'Ungmennafélag Íslands',
        size: 'small',
        users: 6,
        count: 136,
        rank: 121,
    },
    {
        name: 'InfoMentor',
        size: 'small',
        users: 3,
        count: 129,
        rank: 122,
    },
    {
        name: 'Steinull hf',
        size: 'small',
        users: 2,
        count: 124,
        rank: 123,
    },
    {
        name: 'Seðlabankin',
        size: 'large',
        users: 1,
        count: 121,
        rank: 124,
    },
    {
        name: 'Þjóðminjasafn Íslands',
        size: 'small',
        users: 3,
        count: 120,
        rank: 125,
    },
    {
        name: 'Ístak hf.',
        size: 'large',
        users: 4,
        count: 119,
        rank: 126,
    },
    {
        name: 'Verkmenntaskóli Austurlands',
        size: 'small',
        users: 4,
        count: 115,
        rank: 127,
    },
    {
        name: 'Tiro',
        size: 'small',
        users: 4,
        count: 111,
        rank: 128,
    },
    {
        name: 'Heiðarskóli Reykjanesbær ',
        size: 'small',
        users: 3,
        count: 111,
        rank: 129,
    },
    {
        name: 'Landspítali - Grensás ',
        size: 'medium',
        users: 3,
        count: 111,
        rank: 130,
    },
    {
        name: 'Code North',
        size: 'small',
        users: 4,
        count: 109,
        rank: 131,
    },
    {
        name: 'Akranes',
        size: 'large',
        users: 4,
        count: 107,
        rank: 132,
    },
    {
        name: 'Brandenburg',
        size: 'small',
        users: 3,
        count: 105,
        rank: 133,
    },
    {
        name: 'Nesfiskur ehf',
        size: 'medium',
        users: 1,
        count: 104,
        rank: 134,
    },
    {
        name: 'Hvolsskóli',
        size: 'small',
        users: 2,
        count: 102,
        rank: 135,
    },
    {
        name: 'Fjármála- og efnahagsráðuneytið',
        size: 'medium',
        users: 1,
        count: 100,
        rank: 136,
    },
    {
        name: 'Dlm. Vesturlands',
        size: 'small',
        users: 1,
        count: 100,
        rank: 137,
    },
    {
        name: 'Landspítali - fæðingarvakt',
        size: 'medium',
        users: 2,
        count: 99,
        rank: 138,
    },
    {
        name: 'Listasafn Íslands',
        size: 'small',
        users: 4,
        count: 97,
        rank: 139,
    },
    {
        name: 'Uppistandshópurinn VHS',
        size: 'small',
        users: 3,
        count: 95,
        rank: 140,
    },
    {
        name: 'Sense Iceland ',
        size: 'small',
        users: 1,
        count: 95,
        rank: 141,
    },
    {
        name: 'Sendiráð Íslands í París',
        size: 'small',
        users: 3,
        count: 90,
        rank: 142,
    },
    {
        name: 'Valmenn',
        size: 'small',
        users: 1,
        count: 89,
        rank: 143,
    },
    {
        name: 'Skútaís ',
        size: 'small',
        users: 1,
        count: 86,
        rank: 144,
    },
    {
        name: 'Kléberg ',
        size: 'small',
        users: 5,
        count: 84,
        rank: 145,
    },
    {
        name: 'Listaháskóli Íslands',
        size: 'medium',
        users: 1,
        count: 80,
        rank: 146,
    },
    {
        name: 'Þjóðleikhúsið',
        size: 'medium',
        users: 3,
        count: 80,
        rank: 147,
    },
    {
        name: 'Minor7 Ehf ',
        size: 'small',
        users: 3,
        count: 80,
        rank: 148,
    },
    {
        name: 'Skerpa ehf',
        size: 'small',
        users: 1,
        count: 80,
        rank: 149,
    },
    {
        name: 'Ás styrktarfélag',
        size: 'medium',
        users: 4,
        count: 73,
        rank: 150,
    },
    {
        name: 'Grunnskóli Suðureyrar',
        size: 'small',
        users: 4,
        count: 71,
        rank: 151,
    },
    {
        name: 'Kerecis ',
        size: 'small',
        users: 3,
        count: 70,
        rank: 152,
    },
    {
        name: 'Posturinn',
        size: 'large',
        users: 4,
        count: 70,
        rank: 153,
    },
    {
        name: 'Fosshótel Reykjavík',
        size: 'medium',
        users: 1,
        count: 70,
        rank: 154,
    },
    {
        name: 'Selásskóli',
        size: 'small',
        users: 1,
        count: 69,
        rank: 155,
    },
    {
        name: 'Íslenskar orkurannsóknir',
        size: 'small',
        users: 2,
        count: 68,
        rank: 156,
    },
    {
        name: 'Utanríkisráðuneytið',
        size: 'medium',
        users: 6,
        count: 66,
        rank: 157,
    },
    {
        name: 'Veiðihornið',
        size: 'small',
        users: 4,
        count: 64,
        rank: 158,
    },
    {
        name: 'Inntak',
        size: 'small',
        users: 1,
        count: 63,
        rank: 159,
    },
    {
        name: 'Sidekick Health ',
        size: 'medium',
        users: 1,
        count: 61,
        rank: 160,
    },
    {
        name: 'Heilbrigðisstofnun Suðurnesja ',
        size: 'medium',
        users: 2,
        count: 61,
        rank: 161,
    },
    {
        name: 'Rými',
        size: 'small',
        users: 2,
        count: 60,
        rank: 162,
    },
    {
        name: 'Sýslumaðurinn á Austurlandinu',
        size: 'small',
        users: 1,
        count: 60,
        rank: 163,
    },
    {
        name: 'Faxaflóahafnir sf',
        size: 'small',
        users: 2,
        count: 60,
        rank: 164,
    },
    {
        name: 'Ísblik',
        size: 'small',
        users: 1,
        count: 60,
        rank: 165,
    },
    {
        name: 'Gallerí Voff',
        size: 'small',
        users: 1,
        count: 60,
        rank: 166,
    },
    {
        name: 'Kjarninn',
        size: 'small',
        users: 3,
        count: 60,
        rank: 167,
    },
    {
        name: 'Digido',
        size: 'small',
        users: 2,
        count: 60,
        rank: 168,
    },
    {
        name: 'Jökulá',
        size: 'small',
        users: 2,
        count: 60,
        rank: 169,
    },
    {
        name: 'Sharp Sheep Iceland ehf',
        size: 'small',
        users: 1,
        count: 60,
        rank: 170,
    },
    {
        name: 'ssbyggir',
        size: 'small',
        users: 1,
        count: 60,
        rank: 171,
    },
    {
        name: 'Sjúkrahúsið á Akureyri',
        size: 'large',
        users: 3,
        count: 59,
        rank: 172,
    },
    {
        name: 'Melaskóli ',
        size: 'small',
        users: 2,
        count: 58,
        rank: 173,
    },
    {
        name: 'heimavinna',
        size: 'small',
        users: 3,
        count: 56,
        rank: 174,
    },
    {
        name: 'Fjölbrautaskóli Suðurlands',
        size: 'medium',
        users: 4,
        count: 55,
        rank: 175,
    },
    {
        name: 'Doorway ehf',
        size: 'small',
        users: 3,
        count: 53,
        rank: 176,
    },
    {
        name: 'Framhaldsskólinn í Austur-Skaftafellssýslu',
        size: 'small',
        users: 3,
        count: 52,
        rank: 177,
    },
    {
        name: 'Aðalraf ehf',
        size: 'small',
        users: 1,
        count: 50,
        rank: 178,
    },
    {
        name: 'Landspítali-geðsvið',
        size: 'small',
        users: 2,
        count: 50,
        rank: 179,
    },
    {
        name: 'Sæplast Iceland ehf.',
        size: 'small',
        users: 1,
        count: 48,
        rank: 180,
    },
    {
        name: 'Storytel',
        size: 'small',
        users: 2,
        count: 41,
        rank: 181,
    },
    {
        name: 'Ríkisútvarpið RUV',
        size: 'small',
        users: 1,
        count: 41,
        rank: 182,
    },
    {
        name: 'Hard Wok Cafe',
        size: 'small',
        users: 4,
        count: 41,
        rank: 183,
    },
    {
        name: 'Hótel Framtíð ehf',
        size: 'small',
        users: 1,
        count: 40,
        rank: 184,
    },
    {
        name: 'Vegagerð Reykjavíkur',
        size: 'medium',
        users: 1,
        count: 40,
        rank: 185,
    },
    {
        name: 'Slökkvilið höfuðborgarsvæðisins ',
        size: 'medium',
        users: 2,
        count: 39,
        rank: 186,
    },
    {
        name: 'The Skyr Factory',
        size: 'small',
        users: 1,
        count: 38,
        rank: 187,
    },
    {
        name: 'Bónus',
        size: 'small',
        users: 3,
        count: 38,
        rank: 188,
    },
    {
        name: 'Dekurdýr',
        size: 'small',
        users: 1,
        count: 35,
        rank: 189,
    },
    {
        name: 'Félagsmiðstöðin Dimma',
        size: 'small',
        users: 1,
        count: 35,
        rank: 190,
    },
    {
        name: 'Partýbær',
        size: 'small',
        users: 1,
        count: 32,
        rank: 191,
    },
    {
        name: 'GT-Verktakar',
        size: 'small',
        users: 1,
        count: 31,
        rank: 192,
    },
    {
        name: 'Krísuvík',
        size: 'small',
        users: 1,
        count: 30,
        rank: 193,
    },
    {
        name: 'Dalskóli',
        size: 'medium',
        users: 1,
        count: 30,
        rank: 194,
    },
    {
        name: 'Minjasafnið á Akureyri',
        size: 'small',
        users: 1,
        count: 30,
        rank: 195,
    },
    {
        name: 'Póstdreifing',
        size: 'small',
        users: 1,
        count: 30,
        rank: 196,
    },
    {
        name: 'S4s',
        size: 'medium',
        users: 1,
        count: 30,
        rank: 197,
    },
    {
        name: 'Blóðbankinn ',
        size: 'small',
        users: 1,
        count: 30,
        rank: 198,
    },
    {
        name: 'Tónlistarskóli Seltjarnarness',
        size: 'small',
        users: 3,
        count: 30,
        rank: 199,
    },
    {
        name: 'Glerárskóli Akureyri',
        size: 'small',
        users: 3,
        count: 30,
        rank: 200,
    },
    {
        name: 'Homestay T14',
        size: 'small',
        users: 1,
        count: 30,
        rank: 201,
    },
    {
        name: 'Kaldrananeshreppur ',
        size: 'small',
        users: 1,
        count: 30,
        rank: 202,
    },
    {
        name: 'Colas Island',
        size: 'small',
        users: 1,
        count: 30,
        rank: 203,
    },
    {
        name: 'Ökuskóli Kjartans',
        size: 'small',
        users: 1,
        count: 30,
        rank: 204,
    },
    {
        name: 'Leikskólinn Reynisholt ',
        size: 'small',
        users: 1,
        count: 30,
        rank: 205,
    },
    {
        name: 'Pretium ehf',
        size: 'small',
        users: 1,
        count: 30,
        rank: 206,
    },
    {
        name: 'Slökkvilið Akureyrar ',
        size: 'small',
        users: 1,
        count: 30,
        rank: 207,
    },
    {
        name: 'VISS vinnu og hæfingarstöð Selfossi',
        size: 'small',
        users: 1,
        count: 29,
        rank: 208,
    },
    {
        name: 'Trésmíði Róberts',
        size: 'small',
        users: 1,
        count: 29,
        rank: 209,
    },
    {
        name: 'Amtsbókasafnið á Akureyri',
        size: 'small',
        users: 2,
        count: 23,
        rank: 210,
    },
    {
        name: 'Ferðafélag Íslands',
        size: 'small',
        users: 2,
        count: 23,
        rank: 211,
    },
    {
        name: 'Ok agency ehf ',
        size: 'small',
        users: 1,
        count: 22,
        rank: 212,
    },
    {
        name: 'Starfsmannafélag Blóðbankans',
        size: 'small',
        users: 3,
        count: 21,
        rank: 213,
    },
    {
        name: 'ENNEMM ',
        size: 'small',
        users: 1,
        count: 20,
        rank: 214,
    },
    {
        name: 'Kaffibrennslan',
        size: 'small',
        users: 2,
        count: 20,
        rank: 215,
    },
    {
        name: 'Brynjar Örnu- og Guðnason',
        size: 'small',
        users: 1,
        count: 20,
        rank: 216,
    },
    {
        name: 'Kramhúsið',
        size: 'small',
        users: 2,
        count: 20,
        rank: 217,
    },
    {
        name: 'Nortek',
        size: 'small',
        users: 2,
        count: 20,
        rank: 218,
    },
    {
        name: 'Rafholt ehf',
        size: 'medium',
        users: 2,
        count: 20,
        rank: 219,
    },
    {
        name: 'Saga Film',
        size: 'small',
        users: 2,
        count: 20,
        rank: 220,
    },
    {
        name: 'Curron ehf.',
        size: 'small',
        users: 1,
        count: 20,
        rank: 221,
    },
    {
        name: 'ÍAV-Íslenskir Aðalverktakar',
        size: 'medium',
        users: 2,
        count: 20,
        rank: 222,
    },
    {
        name: 'Lögmenn Laugavegi 3',
        size: 'small',
        users: 1,
        count: 20,
        rank: 223,
    },
    {
        name: 'Arnar&Arnar.',
        size: 'small',
        users: 1,
        count: 20,
        rank: 224,
    },
    {
        name: 'Crossfit Reykjavík',
        size: 'small',
        users: 1,
        count: 18,
        rank: 225,
    },
    {
        name: 'Tandraberg',
        size: 'small',
        users: 1,
        count: 17,
        rank: 226,
    },
    {
        name: 'Varmahlíðarskóli',
        size: 'small',
        users: 2,
        count: 17,
        rank: 227,
    },
    {
        name: 'Nox Medical',
        size: 'small',
        users: 1,
        count: 15,
        rank: 228,
    },
    {
        name: 'Næsta skref slf',
        size: 'small',
        users: 1,
        count: 15,
        rank: 229,
    },
    {
        name: 'Heilbrigðisstofnun Vestfjarða',
        size: 'medium',
        users: 1,
        count: 14,
        rank: 230,
    },
    {
        name: 'Hlaðgerðarkot-Samhjálp',
        size: 'small',
        users: 1,
        count: 13,
        rank: 231,
    },
    {
        name: 'Sundlaug Akureyrar',
        size: 'small',
        users: 1,
        count: 13,
        rank: 232,
    },
    {
        name: 'Lækjarskóli',
        size: 'small',
        users: 1,
        count: 12,
        rank: 233,
    },
    {
        name: 'Vogar 2',
        size: 'small',
        users: 1,
        count: 12,
        rank: 234,
    },
    {
        name: 'The Laundromat Café',
        size: 'small',
        users: 1,
        count: 11,
        rank: 235,
    },
    {
        name: 'Fjölbrautaskóli Vesturlands á Akranesi',
        size: 'small',
        users: 1,
        count: 11,
        rank: 236,
    },
    {
        name: 'Kadeco',
        size: 'small',
        users: 1,
        count: 10,
        rank: 237,
    },
    {
        name: 'Payday ehf.',
        size: 'small',
        users: 1,
        count: 10,
        rank: 238,
    },
    {
        name: 'Eimskip',
        size: 'large',
        users: 1,
        count: 10,
        rank: 239,
    },
    {
        name: 'Ghaukur slf',
        size: 'small',
        users: 1,
        count: 10,
        rank: 240,
    },
    {
        name: 'Múr og viðhald ehf.',
        size: 'small',
        users: 1,
        count: 10,
        rank: 241,
    },
    {
        name: 'Nordic Wasabi',
        size: 'small',
        users: 1,
        count: 10,
        rank: 242,
    },
    {
        name: 'NPA miðstöðin',
        size: 'medium',
        users: 1,
        count: 10,
        rank: 243,
    },
    {
        name: 'Vivaldi',
        size: 'small',
        users: 1,
        count: 10,
        rank: 244,
    },
    {
        name: 'Flugfélagið Ernir',
        size: 'small',
        users: 1,
        count: 10,
        rank: 245,
    },
    {
        name: 'Ozio',
        size: 'small',
        users: 1,
        count: 10,
        rank: 246,
    },
    {
        name: 'UMFÍ',
        size: 'small',
        users: 1,
        count: 10,
        rank: 247,
    },
    {
        name: 'Driftwood ehf',
        size: 'small',
        users: 1,
        count: 10,
        rank: 248,
    },
    {
        name: 'Vodafone',
        size: 'large',
        users: 1,
        count: 10,
        rank: 249,
    },
    {
        name: 'Gallery Fiskur ',
        size: 'small',
        users: 1,
        count: 10,
        rank: 250,
    },
    {
        name: 'Grant Thornton endurskoðun ehf',
        size: 'small',
        users: 1,
        count: 10,
        rank: 251,
    },
    {
        name: 'Kría hjól',
        size: 'small',
        users: 1,
        count: 10,
        rank: 252,
    },
    {
        name: 'Northern Vision',
        size: 'small',
        users: 1,
        count: 10,
        rank: 253,
    },
    {
        name: 'Bifreiðaverkstæði höfði',
        size: 'small',
        users: 1,
        count: 10,
        rank: 254,
    },
    {
        name: 'Stóru-Vogaskóli',
        size: 'small',
        users: 1,
        count: 10,
        rank: 255,
    },
    {
        name: 'Túnfiskar sf',
        size: 'small',
        users: 1,
        count: 10,
        rank: 256,
    },
    {
        name: 'alma.is',
        size: 'small',
        users: 1,
        count: 9,
        rank: 257,
    },
    {
        name: 'Saltkaup Nordic',
        size: 'small',
        users: 1,
        count: 8,
        rank: 258,
    },
    {
        name: 'Skrudda',
        size: 'small',
        users: 1,
        count: 8,
        rank: 259,
    },
    {
        name: 'B&L',
        size: 'medium',
        users: 2,
        count: 8,
        rank: 260,
    },
    {
        name: 'D6',
        size: 'small',
        users: 1,
        count: 8,
        rank: 261,
    },
    {
        name: 'Rafborg Patreksfirði',
        size: 'small',
        users: 1,
        count: 7,
        rank: 262,
    },
    {
        name: 'Bæjarbakarí',
        size: 'small',
        users: 1,
        count: 5,
        rank: 263,
    },
    {
        name: 'Verkhönnun',
        size: 'small',
        users: 1,
        count: 4,
        rank: 264,
    },
    {
        name: 'Eldriborgari',
        size: 'medium',
        users: 1,
        count: 3,
        rank: 265,
    },
    {
        name: 'HTKR',
        size: 'small',
        users: 1,
        count: 3,
        rank: 266,
    },
    {
        name: 'Kölski',
        size: 'small',
        users: 1,
        count: 2,
        rank: 267,
    },
    {
        name: 'HRM Legal ehf.',
        size: 'small',
        users: 1,
        count: 1,
        rank: 268,
    },
    {
        name: 'Gúmmísteypa Þ. Lárusson',
        size: 'small',
        users: 1,
        count: 1,
        rank: 269,
    },
    {
        name: '1912 ehf',
        size: 'medium',
        count: 0,
        users: 0,
        rank: 270,
    },
    {
        name: 'Adlair AS ehf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 271,
    },
    {
        name: 'Aktíf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 272,
    },
    {
        name: 'Arkitekt Þórarinn',
        size: 'small',
        count: 0,
        users: 0,
        rank: 273,
    },
    {
        name: 'BFJ Málun',
        size: 'small',
        count: 0,
        users: 0,
        rank: 274,
    },
    {
        name: 'Bílhúsið ehf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 275,
    },
    {
        name: 'Boðleið',
        size: 'small',
        count: 0,
        users: 0,
        rank: 276,
    },
    {
        name: 'Bókasafn Kópavogs',
        size: 'small',
        count: 0,
        users: 0,
        rank: 277,
    },
    {
        name: 'Bókasafn Seltjarnarness',
        size: 'small',
        count: 0,
        users: 0,
        rank: 278,
    },
    {
        name: 'Breiðablik Raddir',
        size: 'small',
        count: 0,
        users: 0,
        rank: 279,
    },
    {
        name: 'Corivo ehf.',
        size: 'small',
        count: 0,
        users: 0,
        rank: 280,
    },
    {
        name: 'Dagmamma Laugateigi 27 Rvk',
        size: 'small',
        count: 0,
        users: 0,
        rank: 281,
    },
    {
        name: 'Dýralæknastofa Reyjavíkur ',
        size: 'small',
        count: 0,
        users: 0,
        rank: 282,
    },
    {
        name: 'Félagsmiðstöðin Pegasus',
        size: 'small',
        count: 0,
        users: 0,
        rank: 283,
    },
    {
        name: 'Fjárhúsið á Tjörn ',
        size: 'small',
        count: 0,
        users: 0,
        rank: 284,
    },
    {
        name: 'Fons Juris',
        size: 'small',
        count: 0,
        users: 0,
        rank: 285,
    },
    {
        name: 'Forrhótel Reykjavík',
        size: 'medium',
        count: 0,
        users: 0,
        rank: 286,
    },
    {
        name: 'fylkir ehf.',
        size: 'small',
        count: 0,
        users: 0,
        rank: 287,
    },
    {
        name: 'Genis hf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 288,
    },
    {
        name: 'Gp hönnun',
        size: 'small',
        count: 0,
        users: 0,
        rank: 289,
    },
    {
        name: 'Gröfuþjónusta Steins ehf.',
        size: 'small',
        count: 0,
        users: 0,
        rank: 290,
    },
    {
        name: 'H&M',
        size: 'small',
        count: 0,
        users: 0,
        rank: 291,
    },
    {
        name: 'Haraldsson Prod.',
        size: 'small',
        count: 0,
        users: 0,
        rank: 292,
    },
    {
        name: 'heimavinnir',
        size: 'small',
        count: 0,
        users: 0,
        rank: 293,
    },
    {
        name: 'Heimili',
        size: 'small',
        count: 0,
        users: 0,
        rank: 294,
    },
    {
        name: 'Hekla hf.',
        size: 'medium',
        count: 0,
        users: 0,
        rank: 295,
    },
    {
        name: 'Hilmar Bjarnason',
        size: 'small',
        count: 0,
        users: 0,
        rank: 296,
    },
    {
        name: 'Hönnunarhúsið ehf.',
        size: 'small',
        count: 0,
        users: 0,
        rank: 297,
    },
    {
        name: 'Hraðbúðin Hellissandi',
        size: 'small',
        count: 0,
        users: 0,
        rank: 298,
    },
    {
        name: 'Hugarorka',
        size: 'small',
        count: 0,
        users: 0,
        rank: 299,
    },
    {
        name: 'ION Ráðgjöf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 300,
    },
    {
        name: 'Íslandsstofa',
        size: 'small',
        count: 0,
        users: 0,
        rank: 301,
    },
    {
        name: 'Íspan Glerborg ehf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 302,
    },
    {
        name: 'Íþróttafélag Hafnarfjarðar',
        size: 'large',
        count: 0,
        users: 0,
        rank: 303,
    },
    {
        name: 'JG málun ehf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 304,
    },
    {
        name: 'Jón Ingi Hinriksson ehf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 305,
    },
    {
        name: 'Kanon arkitektar',
        size: 'small',
        count: 0,
        users: 0,
        rank: 306,
    },
    {
        name: 'Kaupfélag Borgfirðinga',
        size: 'small',
        count: 0,
        users: 0,
        rank: 307,
    },
    {
        name: 'Kirkjulundur 6',
        size: 'small',
        count: 0,
        users: 0,
        rank: 308,
    },
    {
        name: 'Kjaran ehf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 309,
    },
    {
        name: 'Kjöthöllin ',
        size: 'small',
        count: 0,
        users: 0,
        rank: 310,
    },
    {
        name: 'kolli ehf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 311,
    },
    {
        name: 'Krónan',
        size: 'large',
        count: 0,
        users: 0,
        rank: 312,
    },
    {
        name: 'Læknavaktin',
        size: 'small',
        count: 0,
        users: 0,
        rank: 313,
    },
    {
        name: 'Laki Power ehf.',
        size: 'small',
        count: 0,
        users: 0,
        rank: 314,
    },
    {
        name: 'Laugarnesvegur ',
        size: 'small',
        count: 0,
        users: 0,
        rank: 315,
    },
    {
        name: 'Leikskólinn Sunnuás',
        size: 'small',
        count: 0,
        users: 0,
        rank: 316,
    },
    {
        name: 'Level 10 heilsuklúbbar',
        size: 'small',
        count: 0,
        users: 0,
        rank: 317,
    },
    {
        name: 'LG-HH2',
        size: 'small',
        count: 0,
        users: 0,
        rank: 318,
    },
    {
        name: 'Línulíf ehf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 319,
    },
    {
        name: 'Ljósheimar',
        size: 'small',
        count: 0,
        users: 0,
        rank: 320,
    },
    {
        name: 'Lucinity ',
        size: 'small',
        count: 0,
        users: 0,
        rank: 321,
    },
    {
        name: 'Máni Pictures ehf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 322,
    },
    {
        name: 'Matseðill ehf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 323,
    },
    {
        name: 'Menntaskólinn á Ísafirði ',
        size: 'small',
        count: 0,
        users: 0,
        rank: 324,
    },
    {
        name: 'Metall',
        size: 'small',
        count: 0,
        users: 0,
        rank: 325,
    },
    {
        name: 'Miðsitja',
        size: 'small',
        count: 0,
        users: 0,
        rank: 326,
    },
    {
        name: 'Mjólkursamsalan',
        size: 'small',
        count: 0,
        users: 0,
        rank: 327,
    },
    {
        name: 'Nútrí Acaí bar',
        size: 'small',
        count: 0,
        users: 0,
        rank: 328,
    },
    {
        name: 'OHS verk',
        size: 'small',
        count: 0,
        users: 0,
        rank: 329,
    },
    {
        name: 'Olís Neskaupstaður ',
        size: 'small',
        count: 0,
        users: 0,
        rank: 330,
    },
    {
        name: 'PuffinTravel',
        size: 'small',
        count: 0,
        users: 0,
        rank: 331,
    },
    {
        name: 'Ráður',
        size: 'small',
        count: 0,
        users: 0,
        rank: 332,
    },
    {
        name: 'Raf og tæknilausnir ',
        size: 'small',
        count: 0,
        users: 0,
        rank: 333,
    },
    {
        name: 'Rafal ehf',
        size: 'medium',
        count: 0,
        users: 0,
        rank: 334,
    },
    {
        name: 'Raflost ehf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 335,
    },
    {
        name: 'Retric ehf.',
        size: 'small',
        count: 0,
        users: 0,
        rank: 336,
    },
    {
        name: 'Réttingaverkstæði Sveins ehf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 337,
    },
    {
        name: 'Ripple',
        size: 'small',
        count: 0,
        users: 0,
        rank: 338,
    },
    {
        name: 'S16 Ehf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 339,
    },
    {
        name: 'Sæti hópferðir',
        size: 'small',
        count: 0,
        users: 0,
        rank: 340,
    },
    {
        name: 'Safari Hjol',
        size: 'small',
        count: 0,
        users: 0,
        rank: 341,
    },
    {
        name: 'Samorka',
        size: 'small',
        count: 0,
        users: 0,
        rank: 342,
    },
    {
        name: 'Sensa',
        size: 'medium',
        count: 0,
        users: 0,
        rank: 343,
    },
    {
        name: 'Siðmennt',
        size: 'small',
        count: 0,
        users: 0,
        rank: 344,
    },
    {
        name: 'Sjóvá',
        size: 'medium',
        count: 0,
        users: 0,
        rank: 345,
    },
    {
        name: 'Stillholt 19   (601), 300 Akranesi.',
        size: 'small',
        count: 0,
        users: 0,
        rank: 346,
    },
    {
        name: 'Strendingur ehf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 347,
    },
    {
        name: 'Sútarinn.ehf',
        size: 'small',
        count: 0,
        users: 0,
        rank: 348,
    },
    {
        name: 'Tamningakona',
        size: 'small',
        count: 0,
        users: 0,
        rank: 349,
    },
    {
        name: 'Tónskóli Sigursveins ',
        size: 'small',
        count: 0,
        users: 0,
        rank: 350,
    },
    {
        name: 'Vínbúðin Hólmavik ',
        size: 'small',
        count: 0,
        users: 0,
        rank: 351,
    },
    {
        name: 'Vogaskóli ',
        size: 'small',
        count: 0,
        users: 0,
        rank: 352,
    },
    {
        name: 'VR',
        size: 'small',
        count: 0,
        users: 0,
        rank: 353,
    },
    {
        name: 'Zenter',
        size: 'small',
        count: 0,
        users: 0,
        rank: 354,
    },
    {
        name: 'Þ.Þorgrimsspn',
        size: 'small',
        count: 0,
        users: 0,
        rank: 355,
    },
    {
        name: 'Þyrluþjónustan Helo',
        size: 'small',
        count: 0,
        users: 0,
        rank: 356,
    },
];

export const genderStats: GenderStat[] = [
    {
        gender: 'kona',
        count: 253831,
    },
    {
        gender: 'karl',
        count: 112235,
    },
    {
        gender: 'annad',
        count: 161,
    },
];

export const ageStats: AgeStat[] = [
    {
        age: '0-9 ára',
        count: 761,
    },
    {
        age: '10-19 ára',
        count: 5275,
    },
    {
        age: '20-29 ára',
        count: 46508,
    },
    {
        age: '30-39 ára',
        count: 75228,
    },
    {
        age: '40-49 ára',
        count: 118670,
    },
    {
        age: '50-59 ára',
        count: 0,
    },
    {
        age: '60-69 ára',
        count: 29703,
    },
    {
        age: '70-79 ára',
        count: 3929,
    },
    {
        age: '80-89 ára',
        count: 10,
    },
    {
        age: '90+ ára',
        count: 1,
    },
];

export const timeline: TimelineStat[] = [
    {
        date: '2021-11-08',
        count: 15928,
    },
    {
        date: '2021-11-09',
        count: 23016,
    },
    {
        date: '2021-11-10',
        count: 46415,
    },
    {
        date: '2021-11-11',
        count: 36737,
    },
    {
        date: '2021-11-12',
        count: 34087,
    },
    {
        date: '2021-11-13',
        count: 40905,
    },
    {
        date: '2021-11-14',
        count: 54521,
    },
    {
        date: '2021-11-15',
        count: 114618,
    },
];
