import { Institution } from '../types/institution';
import { School } from '../types/user';

export const schools: Array<School> = [
    {
        name: 'Hörðuvallaskóli',
        class1_3: 295,
        class4_10: 631,
        total: 926,
        division: 1,
        code: '9D25EEB9',
    },
    {
        name: 'Varmárskóli',
        class1_3: 185,
        class4_10: 631,
        total: 816,
        division: 1,
        code: '1FE2602C',
    },
    {
        name: 'Hagaskóli',
        class1_3: 0,
        class4_10: 570,
        total: 570,
        division: 1,
        code: '476A8F3A',
    },
    {
        name: 'Víðistaðaskóli',
        class1_3: 190,
        class4_10: 527,
        total: 717,
        division: 1,
        code: '27FE1BA3',
    },
    {
        name: 'Hraunvallaskóli',
        class1_3: 188,
        class4_10: 526,
        total: 714,
        division: 1,
        code: '74D8FA87',
    },
    {
        name: 'Garðaskóli',
        class1_3: 0,
        class4_10: 519,
        total: 519,
        division: 1,
        code: '7368D40A',
    },
    {
        name: 'Árbæjarskóli',
        class1_3: 152,
        class4_10: 503,
        total: 655,
        division: 1,
        code: '1BA4959D',
    },
    {
        name: 'Lágafellsskóli',
        class1_3: 164,
        class4_10: 500,
        total: 664,
        division: 1,
        code: '0462D86F',
    },
    {
        name: 'Sunnulækjarskóli',
        class1_3: 214,
        class4_10: 495,
        total: 709,
        division: 1,
        code: '4D4B35F4',
    },
    {
        name: 'Langholtsskóli',
        class1_3: 185,
        class4_10: 494,
        total: 679,
        division: 1,
        code: 'DB973040',
    },
    {
        name: 'Vallaskóli',
        class1_3: 163,
        class4_10: 472,
        total: 635,
        division: 1,
        code: '0585A121',
    },
    {
        name: 'Seljaskóli',
        class1_3: 198,
        class4_10: 469,
        total: 667,
        division: 1,
        code: '0D391EAD',
    },
    {
        name: 'Álfhólsskóli',
        class1_3: 168,
        class4_10: 461,
        total: 629,
        division: 1,
        code: '15F02DDC',
    },
    {
        name: 'Salaskóli',
        class1_3: 145,
        class4_10: 455,
        total: 600,
        division: 1,
        code: '46F3C530',
    },
    {
        name: 'Grundaskóli',
        class1_3: 194,
        class4_10: 445,
        total: 639,
        division: 1,
        code: 'C5445A25',
    },
    {
        name: 'Norðlingaskóli',
        class1_3: 178,
        class4_10: 431,
        total: 609,
        division: 1,
        code: '9DE2E197',
    },
    {
        name: 'Vatnsendaskóli',
        class1_3: 169,
        class4_10: 423,
        total: 592,
        division: 1,
        code: '0D356926',
    },
    {
        name: 'Kársnesskóli',
        class1_3: 180,
        class4_10: 410,
        total: 590,
        division: 1,
        code: '43C6D428',
    },
    {
        name: 'Foldaskóli',
        class1_3: 90,
        class4_10: 406,
        total: 496,
        division: 1,
        code: '388F6058',
    },
    {
        name: 'Réttarholtsskóli',
        class1_3: 0,
        class4_10: 401,
        total: 401,
        division: 1,
        code: '471565BB',
    },
    {
        name: 'Öldutúnsskóli',
        class1_3: 178,
        class4_10: 397,
        total: 575,
        division: 1,
        code: '4D58F54B',
    },
    {
        name: 'Grunnskóli Seltjarnarness',
        class1_3: 173,
        class4_10: 386,
        total: 559,
        division: 1,
        code: '95AC025E',
    },
    {
        name: 'Áslandsskóli',
        class1_3: 126,
        class4_10: 380,
        total: 506,
        division: 1,
        code: '51AE3FFE',
    },
    {
        name: 'Brekkuskóli',
        class1_3: 131,
        class4_10: 380,
        total: 511,
        division: 1,
        code: 'E4FF59FF',
    },
    {
        name: 'Lækjarskóli',
        class1_3: 120,
        class4_10: 371,
        total: 491,
        division: 1,
        code: '4F1346AC',
    },
    {
        name: 'Melaskóli',
        class1_3: 204,
        class4_10: 366,
        total: 570,
        division: 1,
        code: '8C5AB86D',
    },
    {
        name: 'Ölduselsskóli',
        class1_3: 143,
        class4_10: 366,
        total: 509,
        division: 1,
        code: '7927C2B4',
    },
    {
        name: 'Hofsstaðaskóli',
        class1_3: 224,
        class4_10: 364,
        total: 588,
        division: 1,
        code: 'EB2E65ED',
    },
    {
        name: 'Hlíðaskóli',
        class1_3: 152,
        class4_10: 360,
        total: 512,
        division: 1,
        code: 'A461A3C2',
    },
    {
        name: 'Grunnskóli Vestmannaeyja',
        class1_3: 158,
        class4_10: 354,
        total: 512,
        division: 1,
        code: 'A10C530E',
    },
    {
        name: 'Grunnskóli Grindavíkur',
        class1_3: 180,
        class4_10: 352,
        total: 532,
        division: 1,
        code: '184FB456',
    },
    {
        name: 'Rimaskóli',
        class1_3: 174,
        class4_10: 350,
        total: 524,
        division: 1,
        code: 'AD646EA5',
    },
    {
        name: 'Sæmundarskóli',
        class1_3: 134,
        class4_10: 350,
        total: 484,
        division: 1,
        code: '6188BAAF',
    },
    {
        name: 'Laugalækjarskóli',
        class1_3: 0,
        class4_10: 343,
        total: 343,
        division: 1,
        code: 'D4B04985',
    },
    {
        name: 'Lindaskóli',
        class1_3: 125,
        class4_10: 336,
        total: 461,
        division: 1,
        code: '7C1F5E65',
    },
    {
        name: 'Háteigsskóli',
        class1_3: 117,
        class4_10: 334,
        total: 451,
        division: 1,
        code: '4E5ECCF2',
    },
    {
        name: 'Brekkubæjarskóli',
        class1_3: 135,
        class4_10: 332,
        total: 467,
        division: 1,
        code: '4807BCDD',
    },
    {
        name: 'Hólabrekkuskóli',
        class1_3: 176,
        class4_10: 326,
        total: 502,
        division: 1,
        code: '6DB2E3E1',
    },
    {
        name: 'Akurskóli',
        class1_3: 106,
        class4_10: 325,
        total: 431,
        division: 1,
        code: 'B1F43221',
    },
    {
        name: 'Snælandsskóli',
        class1_3: 129,
        class4_10: 321,
        total: 450,
        division: 1,
        code: '0D0197D0',
    },
    {
        name: 'Lundarskóli',
        class1_3: 150,
        class4_10: 316,
        total: 466,
        division: 1,
        code: '17263A4F',
    },
    {
        name: 'Álftanesskóli',
        class1_3: 100,
        class4_10: 309,
        total: 409,
        division: 1,
        code: '943188C6',
    },
    {
        name: 'Austurbæjarskóli',
        class1_3: 92,
        class4_10: 304,
        total: 396,
        division: 1,
        code: 'C6F3563B',
    },
    {
        name: 'Holtaskóli',
        class1_3: 95,
        class4_10: 301,
        total: 396,
        division: 1,
        code: 'B100FBCB',
    },
    {
        name: 'Setbergsskóli',
        class1_3: 127,
        class4_10: 299,
        total: 426,
        division: 1,
        code: 'EECA93CA',
    },
    {
        name: 'Heiðarskóli (Reykjanesbæ)',
        class1_3: 121,
        class4_10: 297,
        total: 418,
        division: 1,
        code: '1C2DAA67',
    },
    {
        name: 'Breiðholtsskóli',
        class1_3: 129,
        class4_10: 295,
        total: 424,
        division: 1,
        code: '91286379',
    },
    {
        name: 'Flataskóli',
        class1_3: 157,
        class4_10: 294,
        total: 451,
        division: 1,
        code: 'A1351DF6',
    },
    {
        name: 'Ingunnarskóli',
        class1_3: 97,
        class4_10: 291,
        total: 388,
        division: 1,
        code: 'FA8C054E',
    },
    {
        name: 'Laugarnesskóli',
        class1_3: 269,
        class4_10: 288,
        total: 557,
        division: 1,
        code: 'DCE30A2A',
    },
    {
        name: 'Álftamýrarskóli',
        class1_3: 0,
        class4_10: 380,
        total: 380,
        division: 2,
        code: '8PI7UHFC',
    },
    {
        name: 'Hvaleyrarskóli',
        class1_3: 127,
        class4_10: 284,
        total: 411,
        division: 2,
        code: 'F4E32E4C',
    },
    {
        name: 'Njarðvíkurskóli',
        class1_3: 124,
        class4_10: 284,
        total: 408,
        division: 2,
        code: '30465ADF',
    },
    {
        name: 'Smáraskóli',
        class1_3: 144,
        class4_10: 279,
        total: 423,
        division: 2,
        code: 'B415ABEB',
    },
    {
        name: 'Naustaskóli',
        class1_3: 107,
        class4_10: 279,
        total: 386,
        division: 2,
        code: 'D9FCE8A7',
    },
    {
        name: 'Giljaskóli',
        class1_3: 109,
        class4_10: 278,
        total: 387,
        division: 2,
        code: '96A425DC',
    },
    {
        name: 'Grunnskólinn í Hveragerði',
        class1_3: 123,
        class4_10: 257,
        total: 380,
        division: 2,
        code: '4251098D',
    },
    {
        name: 'Grunnskólinn á Ísafirði',
        class1_3: 119,
        class4_10: 255,
        total: 374,
        division: 2,
        code: '28EA4BA4',
    },
    {
        name: 'Myllubakkaskóli',
        class1_3: 113,
        class4_10: 254,
        total: 367,
        division: 2,
        code: 'F6A37041',
    },
    {
        name: 'Glerárskóli',
        class1_3: 113,
        class4_10: 250,
        total: 363,
        division: 2,
        code: 'C1C6016C',
    },
    {
        name: 'Grunnskólinn Egilsstöðum og Eiðum/Egilsstaðaskóli',
        class1_3: 120,
        class4_10: 248,
        total: 368,
        division: 2,
        code: 'F94F0E52',
    },
    {
        name: 'Kópavogsskóli',
        class1_3: 125,
        class4_10: 246,
        total: 371,
        division: 2,
        code: 'C16A662B',
    },
    {
        name: 'Árskóli',
        class1_3: 113,
        class4_10: 246,
        total: 359,
        division: 2,
        code: '43DBEF15',
    },
    {
        name: 'Síðuskóli',
        class1_3: 119,
        class4_10: 244,
        total: 363,
        division: 2,
        code: '403EBED1',
    },
    {
        name: 'Vogaskóli',
        class1_3: 90,
        class4_10: 240,
        total: 330,
        division: 2,
        code: '2D313C3D',
    },
    {
        name: 'Fellaskóli (Reykjavík)',
        class1_3: 87,
        class4_10: 235,
        total: 322,
        division: 2,
        code: '7116A210',
    },
    {
        name: 'Sjálandsskóli',
        class1_3: 70,
        class4_10: 231,
        total: 301,
        division: 2,
        code: 'D3C5E19F',
    },
    {
        name: 'Grunnskólinn í Borgarnesi',
        class1_3: 78,
        class4_10: 223,
        total: 301,
        division: 2,
        code: '67D2876F',
    },
    {
        name: 'Breiðagerðisskóli',
        class1_3: 180,
        class4_10: 222,
        total: 402,
        division: 2,
        code: '7D4880B2',
    },
    {
        name: 'Vesturbæjarskóli',
        class1_3: 129,
        class4_10: 217,
        total: 346,
        division: 2,
        code: 'E27ECD54',
    },
    {
        name: 'Háaleitisskóli (Reykjanesbæ)',
        class1_3: 76,
        class4_10: 212,
        total: 288,
        division: 2,
        code: '444E6462',
    },
    {
        name: 'Borgarhólsskóli',
        class1_3: 73,
        class4_10: 212,
        total: 285,
        division: 2,
        code: '382F08E3',
    },
    {
        name: 'Fossvogsskóli',
        class1_3: 125,
        class4_10: 202,
        total: 327,
        division: 2,
        code: 'B4DB6424',
    },
    {
        name: 'Dalskóli',
        class1_3: 102,
        class4_10: 197,
        total: 299,
        division: 2,
        code: 'B4B6EB4A',
    },
    {
        name: 'Grandaskóli',
        class1_3: 160,
        class4_10: 194,
        total: 354,
        division: 2,
        code: '84B0FEB3',
    },
    {
        name: 'Grunnskólinn í Sandgerði',
        class1_3: 81,
        class4_10: 185,
        total: 266,
        division: 2,
        code: 'F388D089',
    },
    {
        name: 'Landakotsskóli',
        class1_3: 75,
        class4_10: 178,
        total: 253,
        division: 2,
        code: '087FE70B',
    },
    {
        name: 'Grunnskóli Hornafjarðar',
        class1_3: 73,
        class4_10: 172,
        total: 245,
        division: 2,
        code: 'C340A24F',
    },
    {
        name: 'Grunnskólinn í Þorlákshöfn',
        class1_3: 73,
        class4_10: 164,
        total: 237,
        division: 2,
        code: '00470D78',
    },
    {
        name: 'Gerðaskóli',
        class1_3: 77,
        class4_10: 161,
        total: 238,
        division: 2,
        code: '6664874C',
    },
    {
        name: 'Grunnskóli Snæfellsbæjar',
        class1_3: 71,
        class4_10: 160,
        total: 231,
        division: 2,
        code: 'F0B381F9',
    },
    {
        name: 'Hvolsskóli',
        class1_3: 72,
        class4_10: 160,
        total: 232,
        division: 2,
        code: 'AA24D1D3',
    },
    {
        name: 'Nesskóli',
        class1_3: 69,
        class4_10: 156,
        total: 225,
        division: 2,
        code: 'F2A9CBBF',
    },
    {
        name: 'Dalvíkurskóli',
        class1_3: 63,
        class4_10: 148,
        total: 211,
        division: 2,
        code: '8A87E1BC',
    },
    {
        name: 'Oddeyrarskóli',
        class1_3: 55,
        class4_10: 144,
        total: 199,
        division: 2,
        code: 'F3968246',
    },
    {
        name: 'Grunnskóli Reyðarfjarðar',
        class1_3: 68,
        class4_10: 138,
        total: 206,
        division: 2,
        code: 'D905EC11',
    },
    {
        name: 'Grunnskóli Fjallabyggðar',
        class1_3: 63,
        class4_10: 137,
        total: 200,
        division: 2,
        code: '0CAD42DA',
    },
    {
        name: 'Skarðshlíðarskóli',
        class1_3: 84,
        class4_10: 131,
        total: 215,
        division: 2,
        code: '1263E1D9',
    },
    {
        name: 'Selásskóli',
        class1_3: 85,
        class4_10: 128,
        total: 213,
        division: 2,
        code: 'EA1A50D9',
    },
    {
        name: 'Grunnskóli Húnaþings vestra',
        class1_3: 43,
        class4_10: 123,
        total: 166,
        division: 2,
        code: '31DBE0F0',
    },
    {
        name: 'Hvassaleitisskóli',
        class1_3: 0,
        class4_10: 180,
        total: 180,
        division: 2,
        code: 'KV5EElAB',
    },
    {
        name: 'Grunnskóli Borgarfjarðar',
        class1_3: 52,
        class4_10: 121,
        total: 173,
        division: 2,
        code: 'D69C78D2',
    },
    {
        name: 'Stóru-Vogaskóli',
        class1_3: 42,
        class4_10: 120,
        total: 162,
        division: 2,
        code: '7D94EB88',
    },
    {
        name: 'Ártúnsskóli',
        class1_3: 80,
        class4_10: 110,
        total: 190,
        division: 2,
        code: '59420852',
    },
    {
        name: 'Hrafnagilsskóli',
        class1_3: 48,
        class4_10: 110,
        total: 158,
        division: 2,
        code: '9A52D7C6',
    },
    {
        name: 'Grunnskólinn á Eskifirði',
        class1_3: 41,
        class4_10: 110,
        total: 151,
        division: 2,
        code: 'F35CEEA9',
    },
    {
        name: 'Grunnskólinn í Stykkishólmi',
        class1_3: 46,
        class4_10: 104,
        total: 150,
        division: 2,
        code: '7562A5D5',
    },
    {
        name: 'Húsaskóli',
        class1_3: 57,
        class4_10: 97,
        total: 154,
        division: 2,
        code: '516F5BB8',
    },
    {
        name: 'Grunnskólinn á Blönduósi/Blönduskóli',
        class1_3: 41,
        class4_10: 97,
        total: 138,
        division: 2,
        code: '0356BB21',
    },
    {
        name: 'Grunnskóli Bolungarvíkur',
        class1_3: 38,
        class4_10: 93,
        total: 131,
        division: 2,
        code: '9C136EA4',
    },
    {
        name: 'Barnaskólinn á Eyrarbakka og Stokkseyri',
        class1_3: 46,
        class4_10: 90,
        total: 136,
        division: 2,
        code: '6369AC84',
    },
    {
        name: 'Grunnskólinn á Hellu',
        class1_3: 39,
        class4_10: 87,
        total: 126,
        division: 2,
        code: 'CAF5CC75',
    },
    {
        name: 'Klébergsskóli',
        class1_3: 37,
        class4_10: 84,
        total: 121,
        division: 2,
        code: '9195923F',
    },
    {
        name: 'Hamraskóli',
        class1_3: 93,
        class4_10: 82,
        total: 175,
        division: 2,
        code: '45242BA4',
    },
    {
        name: 'Klettaskóli',
        class1_3: 36,
        class4_10: 79,
        total: 115,
        division: 3,
        code: '8FD914A9',
    },
    {
        name: 'Flóaskóli',
        class1_3: 25,
        class4_10: 78,
        total: 103,
        division: 3,
        code: '646E31D6',
    },
    {
        name: 'Varmahlíðarskóli',
        class1_3: 28,
        class4_10: 75,
        total: 103,
        division: 3,
        code: '6102AB1C',
    },
    {
        name: 'Helgafellsskóli',
        class1_3: 79,
        class4_10: 74,
        total: 153,
        division: 3,
        code: 'DEA82EDF',
    },
    {
        name: 'Flúðaskóli',
        class1_3: 15,
        class4_10: 74,
        total: 89,
        division: 3,
        code: '97EDBCFB',
    },
    {
        name: 'Alþjóðaskólinn á Íslandi',
        class1_3: 26,
        class4_10: 71,
        total: 97,
        division: 3,
        code: 'BC848F0C',
    },
    {
        name: 'Auðarskóli',
        class1_3: 21,
        class4_10: 68,
        total: 89,
        division: 3,
        code: 'D4A496F2',
    },
    {
        name: 'Fellaskóli (Fellabæ)',
        class1_3: 32,
        class4_10: 68,
        total: 100,
        division: 3,
        code: '8BB21679',
    },
    {
        name: 'Grunnskóli Fáskrúðsfjarðar',
        class1_3: 30,
        class4_10: 67,
        total: 97,
        division: 3,
        code: 'B89571E0',
    },
    {
        name: 'Waldorfskólinn Sólstafir',
        class1_3: 34,
        class4_10: 64,
        total: 98,
        division: 3,
        code: '5E3A3905',
    },
    {
        name: 'Höfðaskóli',
        class1_3: 25,
        class4_10: 63,
        total: 88,
        division: 3,
        code: '8337F266',
    },
    {
        name: 'NÚ',
        class1_3: 0,
        class4_10: 59,
        total: 59,
        division: 3,
        code: 'FCFC245A',
    },
    {
        name: 'Bláskógaskóli - Reykholti',
        class1_3: 24,
        class4_10: 59,
        total: 83,
        division: 3,
        code: '3C63DFC8',
    },
    {
        name: 'Heiðarskóli (Leirársveit)',
        class1_3: 19,
        class4_10: 56,
        total: 75,
        division: 3,
        code: '5BD64E04',
    },
    {
        name: 'Vopnafjarðarskóli',
        class1_3: 29,
        class4_10: 56,
        total: 85,
        division: 3,
        code: '98710176',
    },
    {
        name: 'Grunnskóli Vesturbyggðar/Patreksskóli',
        class1_3: 26,
        class4_10: 55,
        total: 81,
        division: 3,
        code: 'D4D99C8F',
    },
    {
        name: 'Laugalandsskóli í Holtum',
        class1_3: 22,
        class4_10: 54,
        total: 76,
        division: 3,
        code: '57435518',
    },
    {
        name: 'Grunnskóli Grundarfjarðar',
        class1_3: 38,
        class4_10: 53,
        total: 91,
        division: 3,
        code: '41FE7B8E',
    },
    {
        name: 'Grunnskóli Djúpavogs/Djúpavogsskóli',
        class1_3: 23,
        class4_10: 52,
        total: 75,
        division: 3,
        code: 'F1E61943',
    },
    {
        name: 'Grunnskólinn austan Vatna',
        class1_3: 13,
        class4_10: 51,
        total: 64,
        division: 3,
        code: '9B8573B3',
    },
    {
        name: 'Þingeyjarskóli',
        class1_3: 14,
        class4_10: 51,
        total: 65,
        division: 3,
        code: 'DD8B54F9',
    },
    {
        name: 'Tjarnarskóli',
        class1_3: 0,
        class4_10: 50,
        total: 50,
        division: 3,
        code: '01B214E5',
    },
    {
        name: 'Stapaskóli',
        class1_3: 87,
        class4_10: 50,
        total: 137,
        division: 3,
        code: '55ECDB95',
    },
    {
        name: 'Þelamerkurskóli',
        class1_3: 15,
        class4_10: 50,
        total: 65,
        division: 3,
        code: 'D4284CE5',
    },
    {
        name: 'Seyðisfjarðarskóli',
        class1_3: 22,
        class4_10: 50,
        total: 72,
        division: 3,
        code: '8F66F955',
    },
    {
        name: 'Waldorfskólinn Lækjarbotnum',
        class1_3: 11,
        class4_10: 48,
        total: 59,
        division: 3,
        code: 'CD21790E',
    },
    {
        name: 'Grunnskólinn á Þórshöfn',
        class1_3: 19,
        class4_10: 48,
        total: 67,
        division: 3,
        code: 'E1F43FFB',
    },
    {
        name: 'Barnaskóli Hjallastefnunnar Reykjavík',
        class1_3: 78,
        class4_10: 44,
        total: 122,
        division: 3,
        code: 'B42FC9C8',
    },
    {
        name: 'Skóli Ísaks Jónssonar',
        class1_3: 157,
        class4_10: 43,
        total: 200,
        division: 3,
        code: '24B52659',
    },
    {
        name: 'Barnaskóli Hjallastefnunnar á Vífilsstöðum',
        class1_3: 45,
        class4_10: 37,
        total: 82,
        division: 3,
        code: 'A89BCB33',
    },
    {
        name: 'Grenivíkurskóli',
        class1_3: 14,
        class4_10: 36,
        total: 50,
        division: 3,
        code: '35256F14',
    },
    {
        name: 'Bláskógaskóli - Laugarvatni',
        class1_3: 16,
        class4_10: 35,
        total: 51,
        division: 3,
        code: 'D7D12792',
    },
    {
        name: 'Suðurhlíðarskóli',
        class1_3: 6,
        class4_10: 34,
        total: 40,
        division: 3,
        code: 'E0CC8C08',
    },
    {
        name: 'Valsárskóli',
        class1_3: 15,
        class4_10: 34,
        total: 49,
        division: 3,
        code: '9E0CF6A9',
    },
    {
        name: 'Grunnskóli Mýrdalshrepps/Víkurskóli',
        class1_3: 19,
        class4_10: 34,
        total: 53,
        division: 3,
        code: 'EB556DB7',
    },
    {
        name: 'Reykhólaskóli',
        class1_3: 11,
        class4_10: 33,
        total: 44,
        division: 3,
        code: '0FD12DD5',
    },
    {
        name: 'Brúarásskóli',
        class1_3: 6,
        class4_10: 33,
        total: 39,
        division: 3,
        code: '38CD7954',
    },
    {
        name: 'Brúarskóli',
        class1_3: 0,
        class4_10: 32,
        total: 32,
        division: 3,
        code: '16C606EE',
    },
    {
        name: 'Þjórsárskóli',
        class1_3: 14,
        class4_10: 32,
        total: 46,
        division: 3,
        code: 'B3919524',
    },
    {
        name: 'Grunnskólinn Suðureyri/Suðureyrarskóli',
        class1_3: 12,
        class4_10: 31,
        total: 43,
        division: 3,
        code: '0DEB6DF1',
    },
    {
        name: 'Grunnskólinn á Tálknafirði',
        class1_3: 9,
        class4_10: 30,
        total: 39,
        division: 3,
        code: '026B7E57',
    },
    {
        name: 'Öxarfjarðarskóli',
        class1_3: 0,
        class4_10: 29,
        total: 29,
        division: 3,
        code: 'WHZU07YU',
    },
    {
        name: 'Reykjahlíðarskóli',
        class1_3: 12,
        class4_10: 29,
        total: 41,
        division: 3,
        code: 'DC89CE01',
    },
    {
        name: 'Kirkjubæjarskóli',
        class1_3: 13,
        class4_10: 28,
        total: 41,
        division: 3,
        code: 'ACD0E0A0',
    },
    {
        name: 'Húnavallaskóli',
        class1_3: 9,
        class4_10: 27,
        total: 36,
        division: 3,
        code: '4672CFC1',
    },
    {
        name: 'Grunnskólinn á Hólmavík',
        class1_3: 15,
        class4_10: 26,
        total: 41,
        division: 3,
        code: 'B458DF35',
    },
    {
        name: 'Kerhólsskóli',
        class1_3: 21,
        class4_10: 26,
        total: 47,
        division: 3,
        code: 'A817DACC',
    },
    {
        name: 'Stórutjarnaskóli',
        class1_3: 11,
        class4_10: 25,
        total: 36,
        division: 3,
        code: 'BA940585',
    },
    {
        name: 'Grunnskólinn Þingeyri',
        class1_3: 11,
        class4_10: 24,
        total: 35,
        division: 3,
        code: 'D7057255',
    },
    {
        name: 'Krikaskóli',
        class1_3: 79,
        class4_10: 21,
        total: 100,
        division: 3,
        code: '7CBDD51A',
    },
    {
        name: 'Bíldudalsskóli',
        class1_3: 10,
        class4_10: 19,
        total: 29,
        division: 3,
        code: 'F0AFBF3F',
    },
    {
        name: 'Urriðaholtsskóli',
        class1_3: 35,
        class4_10: 18,
        total: 53,
        division: 3,
        code: '327E5EE5',
    },
    {
        name: 'Súðavíkurskóli',
        class1_3: 3,
        class4_10: 18,
        total: 21,
        division: 3,
        code: 'A36DD8D3',
    },
    {
        name: 'Breiðdals- og Stöðvarfjarðarskóli',
        class1_3: 7,
        class4_10: 15,
        total: 22,
        division: 3,
        code: '5565A347',
    },
    {
        name: 'Hlíðarskóli',
        class1_3: 1,
        class4_10: 14,
        total: 15,
        division: 3,
        code: 'E546A6CB',
    },
    {
        name: 'Árskógarskóli',
        class1_3: 8,
        class4_10: 14,
        total: 22,
        division: 3,
        code: '9B31A7AD',
    },
    {
        name: 'Grunnskólinn í Hrísey/Hríseyjarskóli',
        class1_3: 3,
        class4_10: 13,
        total: 16,
        division: 3,
        code: '230B6933',
    },
    {
        name: 'Arnarskóli',
        class1_3: 5,
        class4_10: 11,
        total: 16,
        division: 3,
        code: 'C88B77BB',
    },
    {
        name: 'Laugargerðisskóli',
        class1_3: 7,
        class4_10: 11,
        total: 18,
        division: 3,
        code: '15693E79',
    },
    {
        name: 'Grunnskóli Önundarfjarðar',
        class1_3: 5,
        class4_10: 10,
        total: 15,
        division: 3,
        code: '33F68522',
    },
    {
        name: 'Barnaskóli Hjallastefnunnar við Hjallabraut',
        class1_3: 60,
        class4_10: 9,
        total: 69,
        division: 3,
        code: '8A5C3B76',
    },
    {
        name: 'Grunnskólinn á Drangsnesi',
        class1_3: 3,
        class4_10: 4,
        total: 7,
        division: 3,
        code: 'CC711D4F',
    },
    {
        name: 'Grunnskóli Borgarfjarðar eystri',
        class1_3: 0,
        class4_10: 4,
        total: 4,
        division: 3,
        code: '5503E871',
    },
    {
        name: 'Grunnskólinn á Raufarhöfn',
        class1_3: 3,
        class4_10: 3,
        total: 6,
        division: 3,
        code: 'A3FBE1D6',
    },
    {
        name: 'Grunnskólinn í Hofgarði',
        class1_3: 4,
        class4_10: 3,
        total: 7,
        division: 3,
        code: '15823703',
    },
    {
        name: 'Engjaskóli',
        class1_3: 130,
        class4_10: 114,
        total: 244,
        division: 2,
        code: '23128346',
    },
    {
        name: 'Borgaskóli',
        class1_3: 0,
        class4_10: 0,
        total: 320,
        division: 1,
        code: 'EB3109A6',
    },
    {
        name: 'Víkurskóli',
        class1_3: 0,
        class4_10: 230,
        total: 230,
        division: 2,
        code: 'E11D630A',
    },
];

export const schoolsAsInstitutions: Array<Institution> = [
    {
        name: 'Hörðuvallaskóli',
        id: '9D25EEB9',
        size: 'small',
    },
    {
        name: 'Varmárskóli',
        id: '1FE2602C',
        size: 'small',
    },
    {
        name: 'Hagaskóli',
        id: '476A8F3A',
        size: 'small',
    },
    {
        name: 'Víðistaðaskóli',
        id: '27FE1BA3',
        size: 'small',
    },
    {
        name: 'Hraunvallaskóli',
        id: '74D8FA87',
        size: 'small',
    },
    {
        name: 'Garðaskóli',
        id: '7368D40A',
        size: 'small',
    },
    {
        name: 'Árbæjarskóli',
        id: '1BA4959D',
        size: 'small',
    },
    {
        name: 'Lágafellsskóli',
        id: '0462D86F',
        size: 'small',
    },
    {
        name: 'Sunnulækjarskóli',
        id: '4D4B35F4',
        size: 'small',
    },
    {
        name: 'Langholtsskóli',
        id: 'DB973040',
        size: 'small',
    },
    {
        name: 'Vallaskóli',
        id: '0585A121',
        size: 'small',
    },
    {
        name: 'Seljaskóli',
        id: '0D391EAD',
        size: 'small',
    },
    {
        name: 'Álfhólsskóli',
        id: '15F02DDC',
        size: 'small',
    },
    {
        name: 'Salaskóli',
        id: '46F3C530',
        size: 'small',
    },
    {
        name: 'Grundaskóli',
        id: 'C5445A25',
        size: 'small',
    },
    {
        name: 'Norðlingaskóli',
        id: '9DE2E197',
        size: 'small',
    },
    {
        name: 'Vatnsendaskóli',
        id: '0D356926',
        size: 'small',
    },
    {
        name: 'Kársnesskóli',
        id: '43C6D428',
        size: 'small',
    },
    {
        name: 'Foldaskóli',
        id: '388F6058',
        size: 'small',
    },
    {
        name: 'Réttarholtsskóli',
        id: '471565BB',
        size: 'small',
    },
    {
        name: 'Öldutúnsskóli',
        id: '4D58F54B',
        size: 'small',
    },
    {
        name: 'Grunnskóli Seltjarnarness',
        id: '95AC025E',
        size: 'small',
    },
    {
        name: 'Áslandsskóli',
        id: '51AE3FFE',
        size: 'small',
    },
    {
        name: 'Brekkuskóli',
        id: 'E4FF59FF',
        size: 'small',
    },
    {
        name: 'Lækjarskóli',
        id: '4F1346AC',
        size: 'small',
    },
    {
        name: 'Melaskóli',
        id: '8C5AB86D',
        size: 'small',
    },
    {
        name: 'Ölduselsskóli',
        id: '7927C2B4',
        size: 'small',
    },
    {
        name: 'Hofsstaðaskóli',
        id: 'EB2E65ED',
        size: 'small',
    },
    {
        name: 'Hlíðaskóli',
        id: 'A461A3C2',
        size: 'small',
    },
    {
        name: 'Grunnskóli Vestmannaeyja',
        id: 'A10C530E',
        size: 'small',
    },
    {
        name: 'Grunnskóli Grindavíkur',
        id: '184FB456',
        size: 'small',
    },
    {
        name: 'Rimaskóli',
        id: 'AD646EA5',
        size: 'small',
    },
    {
        name: 'Sæmundarskóli',
        id: '6188BAAF',
        size: 'small',
    },
    {
        name: 'Laugalækjarskóli',
        id: 'D4B04985',
        size: 'small',
    },
    {
        name: 'Lindaskóli',
        id: '7C1F5E65',
        size: 'small',
    },
    {
        name: 'Háteigsskóli',
        id: '4E5ECCF2',
        size: 'small',
    },
    {
        name: 'Brekkubæjarskóli',
        id: '4807BCDD',
        size: 'small',
    },
    {
        name: 'Hólabrekkuskóli',
        id: '6DB2E3E1',
        size: 'small',
    },
    {
        name: 'Akurskóli',
        id: 'B1F43221',
        size: 'small',
    },
    {
        name: 'Snælandsskóli',
        id: '0D0197D0',
        size: 'small',
    },
    {
        name: 'Lundarskóli',
        id: '17263A4F',
        size: 'small',
    },
    {
        name: 'Álftanesskóli',
        id: '943188C6',
        size: 'small',
    },
    {
        name: 'Austurbæjarskóli',
        id: 'C6F3563B',
        size: 'small',
    },
    {
        name: 'Holtaskóli',
        id: 'B100FBCB',
        size: 'small',
    },
    {
        name: 'Setbergsskóli',
        id: 'EECA93CA',
        size: 'small',
    },
    {
        name: 'Heiðarskóli (Reykjanesbæ)',
        id: '1C2DAA67',
        size: 'small',
    },
    {
        name: 'Breiðholtsskóli',
        id: '91286379',
        size: 'small',
    },
    {
        name: 'Flataskóli',
        id: 'A1351DF6',
        size: 'small',
    },
    {
        name: 'Ingunnarskóli',
        id: 'FA8C054E',
        size: 'small',
    },
    {
        name: 'Laugarnesskóli',
        id: 'DCE30A2A',
        size: 'small',
    },
    {
        name: 'Álftamýrarskóli',
        id: '8PI7UHFC',
        size: 'medium',
    },
    {
        name: 'Hvaleyrarskóli',
        id: 'F4E32E4C',
        size: 'medium',
    },
    {
        name: 'Njarðvíkurskóli',
        id: '30465ADF',
        size: 'medium',
    },
    {
        name: 'Smáraskóli',
        id: 'B415ABEB',
        size: 'medium',
    },
    {
        name: 'Naustaskóli',
        id: 'D9FCE8A7',
        size: 'medium',
    },
    {
        name: 'Giljaskóli',
        id: '96A425DC',
        size: 'medium',
    },
    {
        name: 'Grunnskólinn í Hveragerði',
        id: '4251098D',
        size: 'medium',
    },
    {
        name: 'Grunnskólinn á Ísafirði',
        id: '28EA4BA4',
        size: 'medium',
    },
    {
        name: 'Myllubakkaskóli',
        id: 'F6A37041',
        size: 'medium',
    },
    {
        name: 'Glerárskóli',
        id: 'C1C6016C',
        size: 'medium',
    },
    {
        name: 'Grunnskólinn Egilsstöðum og Eiðum/Egilsstaðaskóli',
        id: 'F94F0E52',
        size: 'medium',
    },
    {
        name: 'Kópavogsskóli',
        id: 'C16A662B',
        size: 'medium',
    },
    {
        name: 'Árskóli',
        id: '43DBEF15',
        size: 'medium',
    },
    {
        name: 'Síðuskóli',
        id: '403EBED1',
        size: 'medium',
    },
    {
        name: 'Vogaskóli',
        id: '2D313C3D',
        size: 'medium',
    },
    {
        name: 'Fellaskóli (Reykjavík)',
        id: '7116A210',
        size: 'medium',
    },
    {
        name: 'Sjálandsskóli',
        id: 'D3C5E19F',
        size: 'medium',
    },
    {
        name: 'Grunnskólinn í Borgarnesi',
        id: '67D2876F',
        size: 'medium',
    },
    {
        name: 'Breiðagerðisskóli',
        id: '7D4880B2',
        size: 'medium',
    },
    {
        name: 'Vesturbæjarskóli',
        id: 'E27ECD54',
        size: 'medium',
    },
    {
        name: 'Háaleitisskóli (Reykjanesbæ)',
        id: '444E6462',
        size: 'medium',
    },
    {
        name: 'Borgarhólsskóli',
        id: '382F08E3',
        size: 'medium',
    },
    {
        name: 'Fossvogsskóli',
        id: 'B4DB6424',
        size: 'medium',
    },
    {
        name: 'Dalskóli',
        id: 'B4B6EB4A',
        size: 'medium',
    },
    {
        name: 'Grandaskóli',
        id: '84B0FEB3',
        size: 'medium',
    },
    {
        name: 'Grunnskólinn í Sandgerði',
        id: 'F388D089',
        size: 'medium',
    },
    {
        name: 'Landakotsskóli',
        id: '087FE70B',
        size: 'medium',
    },
    {
        name: 'Grunnskóli Hornafjarðar',
        id: 'C340A24F',
        size: 'medium',
    },
    {
        name: 'Grunnskólinn í Þorlákshöfn',
        id: '00470D78',
        size: 'medium',
    },
    {
        name: 'Gerðaskóli',
        id: '6664874C',
        size: 'medium',
    },
    {
        name: 'Grunnskóli Snæfellsbæjar',
        id: 'F0B381F9',
        size: 'medium',
    },
    {
        name: 'Hvolsskóli',
        id: 'AA24D1D3',
        size: 'medium',
    },
    {
        name: 'Nesskóli',
        id: 'F2A9CBBF',
        size: 'medium',
    },
    {
        name: 'Dalvíkurskóli',
        id: '8A87E1BC',
        size: 'medium',
    },
    {
        name: 'Oddeyrarskóli',
        id: 'F3968246',
        size: 'medium',
    },
    {
        name: 'Grunnskóli Reyðarfjarðar',
        id: 'D905EC11',
        size: 'medium',
    },
    {
        name: 'Grunnskóli Fjallabyggðar',
        id: '0CAD42DA',
        size: 'medium',
    },
    {
        name: 'Skarðshlíðarskóli',
        id: '1263E1D9',
        size: 'medium',
    },
    {
        name: 'Selásskóli',
        id: 'EA1A50D9',
        size: 'medium',
    },
    {
        name: 'Grunnskóli Húnaþings vestra',
        id: '31DBE0F0',
        size: 'medium',
    },
    {
        name: 'Hvassaleitisskóli',
        id: 'KV5EElAB',
        size: 'medium',
    },
    {
        name: 'Grunnskóli Borgarfjarðar',
        id: 'D69C78D2',
        size: 'medium',
    },
    {
        name: 'Stóru-Vogaskóli',
        id: '7D94EB88',
        size: 'medium',
    },
    {
        name: 'Ártúnsskóli',
        id: '59420852',
        size: 'medium',
    },
    {
        name: 'Hrafnagilsskóli',
        id: '9A52D7C6',
        size: 'medium',
    },
    {
        name: 'Grunnskólinn á Eskifirði',
        id: 'F35CEEA9',
        size: 'medium',
    },
    {
        name: 'Grunnskólinn í Stykkishólmi',
        id: '7562A5D5',
        size: 'medium',
    },
    {
        name: 'Húsaskóli',
        id: '516F5BB8',
        size: 'medium',
    },
    {
        name: 'Grunnskólinn á Blönduósi/Blönduskóli',
        id: '0356BB21',
        size: 'medium',
    },
    {
        name: 'Grunnskóli Bolungarvíkur',
        id: '9C136EA4',
        size: 'medium',
    },
    {
        name: 'Barnaskólinn á Eyrarbakka og Stokkseyri',
        id: '6369AC84',
        size: 'medium',
    },
    {
        name: 'Grunnskólinn á Hellu',
        id: 'CAF5CC75',
        size: 'medium',
    },
    {
        name: 'Klébergsskóli',
        id: '9195923F',
        size: 'medium',
    },
    {
        name: 'Hamraskóli',
        id: '45242BA4',
        size: 'medium',
    },
    {
        name: 'Klettaskóli',
        id: '8FD914A9',
        size: 'large',
    },
    {
        name: 'Flóaskóli',
        id: '646E31D6',
        size: 'large',
    },
    {
        name: 'Varmahlíðarskóli',
        id: '6102AB1C',
        size: 'large',
    },
    {
        name: 'Helgafellsskóli',
        id: 'DEA82EDF',
        size: 'large',
    },
    {
        name: 'Flúðaskóli',
        id: '97EDBCFB',
        size: 'large',
    },
    {
        name: 'Alþjóðaskólinn á Íslandi',
        id: 'BC848F0C',
        size: 'large',
    },
    {
        name: 'Auðarskóli',
        id: 'D4A496F2',
        size: 'large',
    },
    {
        name: 'Fellaskóli (Fellabæ)',
        id: '8BB21679',
        size: 'large',
    },
    {
        name: 'Grunnskóli Fáskrúðsfjarðar',
        id: 'B89571E0',
        size: 'large',
    },
    {
        name: 'Waldorfskólinn Sólstafir',
        id: '5E3A3905',
        size: 'large',
    },
    {
        name: 'Höfðaskóli',
        id: '8337F266',
        size: 'large',
    },
    {
        name: 'NÚ',
        id: 'FCFC245A',
        size: 'large',
    },
    {
        name: 'Bláskógaskóli - Reykholti',
        id: '3C63DFC8',
        size: 'large',
    },
    {
        name: 'Heiðarskóli (Leirársveit)',
        id: '5BD64E04',
        size: 'large',
    },
    {
        name: 'Vopnafjarðarskóli',
        id: '98710176',
        size: 'large',
    },
    {
        name: 'Grunnskóli Vesturbyggðar/Patreksskóli',
        id: 'D4D99C8F',
        size: 'large',
    },
    {
        name: 'Laugalandsskóli í Holtum',
        id: '57435518',
        size: 'large',
    },
    {
        name: 'Grunnskóli Grundarfjarðar',
        id: '41FE7B8E',
        size: 'large',
    },
    {
        name: 'Grunnskóli Djúpavogs/Djúpavogsskóli',
        id: 'F1E61943',
        size: 'large',
    },
    {
        name: 'Grunnskólinn austan Vatna',
        id: '9B8573B3',
        size: 'large',
    },
    {
        name: 'Þingeyjarskóli',
        id: 'DD8B54F9',
        size: 'large',
    },
    {
        name: 'Tjarnarskóli',
        id: '01B214E5',
        size: 'large',
    },
    {
        name: 'Stapaskóli',
        id: '55ECDB95',
        size: 'large',
    },
    {
        name: 'Þelamerkurskóli',
        id: 'D4284CE5',
        size: 'large',
    },
    {
        name: 'Seyðisfjarðarskóli',
        id: '8F66F955',
        size: 'large',
    },
    {
        name: 'Waldorfskólinn Lækjarbotnum',
        id: 'CD21790E',
        size: 'large',
    },
    {
        name: 'Grunnskólinn á Þórshöfn',
        id: 'E1F43FFB',
        size: 'large',
    },
    {
        name: 'Barnaskóli Hjallastefnunnar Reykjavík',
        id: 'B42FC9C8',
        size: 'large',
    },
    {
        name: 'Skóli Ísaks Jónssonar',
        id: '24B52659',
        size: 'large',
    },
    {
        name: 'Barnaskóli Hjallastefnunnar á Vífilsstöðum',
        id: 'A89BCB33',
        size: 'large',
    },
    {
        name: 'Grenivíkurskóli',
        id: '35256F14',
        size: 'large',
    },
    {
        name: 'Bláskógaskóli - Laugarvatni',
        id: 'D7D12792',
        size: 'large',
    },
    {
        name: 'Suðurhlíðarskóli',
        id: 'E0CC8C08',
        size: 'large',
    },
    {
        name: 'Valsárskóli',
        id: '9E0CF6A9',
        size: 'large',
    },
    {
        name: 'Grunnskóli Mýrdalshrepps/Víkurskóli',
        id: 'EB556DB7',
        size: 'large',
    },
    {
        name: 'Reykhólaskóli',
        id: '0FD12DD5',
        size: 'large',
    },
    {
        name: 'Brúarásskóli',
        id: '38CD7954',
        size: 'large',
    },
    {
        name: 'Brúarskóli',
        id: '16C606EE',
        size: 'large',
    },
    {
        name: 'Þjórsárskóli',
        id: 'B3919524',
        size: 'large',
    },
    {
        name: 'Grunnskólinn Suðureyri/Suðureyrarskóli',
        id: '0DEB6DF1',
        size: 'large',
    },
    {
        name: 'Grunnskólinn á Tálknafirði',
        id: '026B7E57',
        size: 'large',
    },
    {
        name: 'Öxarfjarðarskóli',
        id: 'WHZU07YU',
        size: 'large',
    },
    {
        name: 'Reykjahlíðarskóli',
        id: 'DC89CE01',
        size: 'large',
    },
    {
        name: 'Kirkjubæjarskóli',
        id: 'ACD0E0A0',
        size: 'large',
    },
    {
        name: 'Húnavallaskóli',
        id: '4672CFC1',
        size: 'large',
    },
    {
        name: 'Grunnskólinn á Hólmavík',
        id: 'B458DF35',
        size: 'large',
    },
    {
        name: 'Kerhólsskóli',
        id: 'A817DACC',
        size: 'large',
    },
    {
        name: 'Stórutjarnaskóli',
        id: 'BA940585',
        size: 'large',
    },
    {
        name: 'Grunnskólinn Þingeyri',
        id: 'D7057255',
        size: 'large',
    },
    {
        name: 'Krikaskóli',
        id: '7CBDD51A',
        size: 'large',
    },
    {
        name: 'Bíldudalsskóli',
        id: 'F0AFBF3F',
        size: 'large',
    },
    {
        name: 'Urriðaholtsskóli',
        id: '327E5EE5',
        size: 'large',
    },
    {
        name: 'Súðavíkurskóli',
        id: 'A36DD8D3',
        size: 'large',
    },
    {
        name: 'Breiðdals- og Stöðvarfjarðarskóli',
        id: '5565A347',
        size: 'large',
    },
    {
        name: 'Hlíðarskóli',
        id: 'E546A6CB',
        size: 'large',
    },
    {
        name: 'Árskógarskóli',
        id: '9B31A7AD',
        size: 'large',
    },
    {
        name: 'Grunnskólinn í Hrísey/Hríseyjarskóli',
        id: '230B6933',
        size: 'large',
    },
    {
        name: 'Arnarskóli',
        id: 'C88B77BB',
        size: 'large',
    },
    {
        name: 'Laugargerðisskóli',
        id: '15693E79',
        size: 'large',
    },
    {
        name: 'Grunnskóli Önundarfjarðar',
        id: '33F68522',
        size: 'large',
    },
    {
        name: 'Barnaskóli Hjallastefnunnar við Hjallabraut',
        id: '8A5C3B76',
        size: 'large',
    },
    {
        name: 'Grunnskólinn á Drangsnesi',
        id: 'CC711D4F',
        size: 'large',
    },
    {
        name: 'Grunnskóli Borgarfjarðar eystri',
        id: '5503E871',
        size: 'large',
    },
    {
        name: 'Grunnskólinn á Raufarhöfn',
        id: 'A3FBE1D6',
        size: 'large',
    },
    {
        name: 'Grunnskólinn í Hofgarði',
        id: '15823703',
        size: 'large',
    },
    {
        name: 'Engjaskóli',
        id: '23128346',
        size: 'medium',
    },
    {
        name: 'Borgaskóli',
        id: 'EB3109A6',
        size: 'small',
    },
    {
        name: 'Víkurskóli',
        id: 'E11D630A',
        size: 'medium',
    },
];
